/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WindowInfo,
} from '../models/index';
import {
    WindowInfoFromJSON,
    WindowInfoToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Visible Windows
     */
    async visibleWindowsWindowsPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WindowInfo>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/windows`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WindowInfoFromJSON));
    }

    /**
     * Visible Windows
     */
    async visibleWindowsWindowsPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WindowInfo>> {
        const response = await this.visibleWindowsWindowsPostRaw(initOverrides);
        return await response.value();
    }

}
