/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Template
 */
export interface Template {
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Template
     */
    html: string;
    /**
     * 
     * @type {number}
     * @memberof Template
     */
    lastModified: number;
    /**
     * 
     * @type {number}
     * @memberof Template
     */
    created: number;
    /**
     * 
     * @type {number}
     * @memberof Template
     */
    id: number;
}

/**
 * Check if a given object implements the Template interface.
 */
export function instanceOfTemplate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "html" in value;
    isInstance = isInstance && "lastModified" in value;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function TemplateFromJSON(json: any): Template {
    return TemplateFromJSONTyped(json, false);
}

export function TemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Template {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'html': json['html'],
        'lastModified': json['last_modified'],
        'created': json['created'],
        'id': json['id'],
    };
}

export function TemplateToJSON(value?: Template | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'html': value.html,
        'last_modified': value.lastModified,
        'created': value.created,
        'id': value.id,
    };
}

